services:
  db:
    container_name: "postgres"
    image: postgres:latest
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'pwd'
      POSTGRES_DB: 'project'
#    volumes:
#      - ./postgres_data:/var/lib/postgresql
    ports:
        - 5432:5432
  my-app:
    container_name: "my-app"
    build: .
    ports:
      - 5050:5050
    restart: always
    depends_on:
      - db