services:
  db:
    container_name: "postgres"
    image: postgres:latest
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'pwd'
      POSTGRES_DB: 'postgres'
    volumes:
      - ./postgres_data:/var/lib/postgresql
    ports:
        - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 15s
      timeout: 10s
      retries: 2

  my-app:
    container_name: "my-app"
    build: .
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - 9090:9090
    depends_on:
      - my-app

  grafana:
    image: grafana/grafana:9.2.15
    container_name: grafana
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    env_file:
      - grafana/config.monitoring
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    working_dir: /my-app/backend

  migration:
    build: .
    image: my-app
    command: bash -c "alembic upgrade head"
    volumes:
      - ./postgres_data:/var/lib/postgresql
    links:
      - db
    depends_on:
      - db
      - my-app
    working_dir: /my-app/backend
