services:
  db:
    container_name: "postgres"
    image: postgres:latest
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'pwd'
      POSTGRES_DB: 'postgres'
    volumes:
      - ./postgres_data:/var/lib/postgresql
    ports:
        - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 15s
      timeout: 10s
      retries: 2
  my-app:
    container_name: "my-app"
    build: .
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
  migration:
    build: .
    image: my-app
    command: bash -c "cd backend && alembic upgrade head"
    volumes:
      - ./postgres_data:/var/lib/postgresql
    links:
      - db
    depends_on:
      - db
      - my-app
