global:
  scrape_interval: 15s
  evaluation_interval: 10s
#
#rule_files:
#  - "/etc/alertmanager/rules.yml"
#
#alerting:
#  alertmanagers:
#  - static_configs:
#    - targets: ['alertmanager:9093']

scrape_configs:
#  - job_name: 'oncall-web'
#    static_configs:
#      - targets: ['oncall-web:8081']
#
#  - job_name: 'node_exporter'
#    scrape_interval: 15s
#    static_configs:
#      - targets: ['node_exporter:9100']

  - job_name: 'blackbox_http_2xx'
    metrics_path: '/probe'
    params:
      module: [ "http_2xx"]
    relabel_configs:
      - source_labels: [ "__address__" ]
        target_label: "__param_target"
      - source_labels: [ "__param_target" ]
        target_label: "instance"
      - target_label: "__address__"
        replacement: "blackbox_exporter:9115"
    static_configs:
      - targets: [ "oncall-web1:8080", "oncall-web2:8080" ]

  - job_name: 'blackbox_icmp'
    metrics_path: '/probe'
    params:
      module: [ "icmp"]
    relabel_configs:
      - source_labels: [ "__address__" ]
        target_label: "__param_target"
      - source_labels: [ "__param_target" ]
        target_label: "instance"
      - target_label: "__address__"
        replacement: "blackbox_exporter:9115"
    static_configs:
      - targets: [ "oncall-web1", "oncall-web2" ]

  - job_name: 'blackbox_tcp'
    metrics_path: '/probe'
    params:
      module: [ "tcp"]
    relabel_configs:
      - source_labels: [ "__address__" ]
        target_label: "__param_target"
      - source_labels: [ "__param_target" ]
        target_label: "instance"
      - target_label: "__address__"
        replacement: "blackbox_exporter:9115"
    static_configs:
      - targets: [ "oncall-web1:8080", "oncall-web2:8080" ]

  - job_name: 'blackbox_exporter'
    static_configs:
      - targets: ['blackbox_exporter:9115']

#  - job_name: 'oncall_api_metrics_exporter'
#    static_configs:
#      - targets: [ 'oncall_api_metrics_exporter:9099' ]

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: [ 'nginx-exporter:9113' ]